[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile="black"
combine_as_imports = true
include_trailing_comma = true
line_length = 120
multi_line_output = 3
no_lines_before = "LOCALFOLDER"
# Python 3.11 not currently supported as of isort==5.10.1
py_version = 310
remove_redundant_aliases = true
supported_extensions = ["py"]
src_paths = ["aoc"]
